Add link to api settings
crookedneighbor/habitica-node pull request #159
Opened 2017-04-05 18:53 UTC by kandros

2017-04-05 19:09 UTC, crookedneighbor requested changes

2017-04-05 19:09 UTC, crookedneighbor commented on README.md
> +You get find your user id and api token [here](https://habitica.com/#/options/settings/apis)
The link is `https://habitica.com/#/options/settings/api`

2017-04-05 19:09 UTC, crookedneighbor commented on README.md
> +This package is intentionally light and unopinionated. It should be used in conjunction with [Habitica's API documentation](https://habitica.com/apidoc/).
Remove the extra space here.

2017-04-05 19:18 UTC, kandros commented on README.md
> +You get find your user id and api token [here](https://habitica.com/#/options/settings/apis)
ups, fixing

2017-04-05 19:34 UTC, crookedneighbor requested changes

2017-04-05 19:34 UTC, crookedneighbor commented on README.md
> +You get find your user id and api token [here](https://habitica.com/#/options/settings/api).
"You get find" -> "You can find"

2017-04-05 19:44 UTC, kandros commented on README.md
> +You get find your user id and api token [here](https://habitica.com/#/options/settings/api).
today feels like ![](https://cdn.meme.am/cache/instances/folder893/67582893.jpg)

2017-04-06 01:50 UTC, merged

2017-04-06 01:50 UTC, crookedneighbor commented
:+1: